server:
  port: 9000
  servlet:
    context-path: /api/
logging:
  level:
    root: DEBUG
spring:
  application:
    name: api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master